### ISSUE TITLE
IndexError: list index out of range during collect

### ISSUE THREAD

**Issue by DomeJoyce** [Reedwarbler/GAPPadder#12]
Hello, i was running the collect part of the pipeline and i get this error:
"Traceback (most recent call last):
  File "./main.py", line 283, in <module>
    main_func(scommand,sfconfig)
  File "./main.py", line 257, in main_func
    drc.merge_dispatch_reads_for_gaps_v2(left_reads, right_reads)
  File "/home/software/GAPPadder/run_multi_threads_discordant.py", line 213, in merge_dispatch_reads_for_gaps_v2
    temp_field=id_fields[0].split("/")
IndexError: list index out of range"

My configuration.json is below:
"{
    "draft_genome": {
        "fa": "/home/domenico/Scrivania/DATA/Projects/Domi/Zu_crist/ZuCrist_sspace/ZuCrist_sspace.final.scaffolds.fasta"
    },
    "raw_reads": [
		    {
		        "left": "/home/domenico/Scrivania/DATA/Projects/Domi/Zu_crist/300_pairs.4_25.h.R1.fq.gz",
		        "right": "/home/domenico/Scrivania/DATA/Projects/Domi/Zu_crist/300_pairs.4_25.h.R2.fq.gz"
		    },
			{
		        "left": "/home/domenico/Scrivania/DATA/Projects/Domi/Zu_crist/550_pairs.4_25.h.R1.fq.gz",
		        "right": "/home/domenico/Scrivania/DATA/Projects/Domi/Zu_crist/550_pairs.4_25.h.R2.fq.gz"
		    }
	  ],
    "alignments": [
		    {
		        "bam": "/home/domenico/Scrivania/DATA/Projects/Domi/Zu_crist/BWA_sspace/Zu_300p.sorted.bam",
		        "is": "293",
		        "std": "119"
		    },
		    {
		        "bam": "/home/domenico/Scrivania/DATA/Projects/Domi/Zu_crist/BWA_sspace/Zu_550p.sorted.bam",
		        "is": "406",
		        "std": "149"
		    }
	  ],
    "software_path": {
        "bwa": "bwa",
        "samtools": "samtools",
        "velvet": "/home/software/anaconda3/pkgs/velvet-1.2.10-hed695b0_3/bin/",
        "kmc": "/usr/local/bin/",
        "TERefiner": "/home/software/GAPPadder/TERefiner_1",
        "ContigsMerger": "/home/software/GAPPadder/ContigsMerger"
    },
    "parameters": {
    		"working_folder": "/home/domenico/Scrivania/DATA/Projects/Domi/Zu_crist/GAPPadder_out",
        "min_gap_size": "1",
        "flank_length": "300",
        "nthreads": "35",
        "verbose": "1"
		},
		"kmer_length": [{
						"k": 30,
						"k_velvet": [{
								"k": 29
						}, 
						{
								"k": 27
						}]
				}, 
				{
						"k": 40,
						"k_velvet": [{
								"k": 39
						}, 
						{
								"k": 37
						}]
				},
				{
						"k": 50,
						"k_velvet": [{
								"k": 49
						}, 
						{
								"k": 47
						}]
				},
				{
						"k": 60,
						"k_velvet": [{
								"k": 59
						}, 
						{
								"k": 57
						}]
				}]
}"

Can you help me to understand the problem and to fix it?

**Comment by Brent-Saylor-Canopy** [comment]
I had the same issue. Check this issue page https://github.com/simoncchu/GAPPadder/issues/3
