### ISSUE TITLE
Arange error, don't know how to solve

### ISSUE THREAD

**Issue by margaretc-ho** [Reedwarbler/GAPPadder#15]
Hi @simoncchu 

I was able to run the Preprocess and Collect steps, but during assembly this is the error message that I get:

```
First round assembly and merger...
**
***
*
Stage 1: 0%
Stage 1: 100%
Stage 2: 0%
Stage 2: 100%
Stage 1: 0%
Stage 1: 100%
Stage 2: 0%
Stage 2: 63%
Stage 2: 90%
Stage 2: 99%
Stage 2: 100%
Stage 1: 0%
Stage 1: 100%
Stage 2: 0%
Stage 2: 35%
Stage 2: 67%
Stage 2: 84%
Stage 2: 89%
Stage 2: 93%
Stage 2: 94%
Stage 2: 96%
Stage 2: 97%
Stage 2: 98%
Stage 2: 99%
Stage 2: 100%
**
**
Stage 1: 0%
Stage 1: 100%
Stage 2: 0%
Stage 2: 100%
Stage 1: 0%
Stage 1: 100%
Stage 2: 0%
Stage 2: 63%
Stage 2: 90%
Stage 2: 99%
Stage 2: 100%
**
Stage 1: 0%
Stage 1: 100%
Stage 2: 0%
Stage 2: 100%
**
**
Stage 1: 0%
Stage 1: 100%
Stage 2: 0%
Stage 2: 79%
Stage 2: 99%
Stage 2: 100%
Stage 1: 0%
Stage 1: 100%
**
Stage 2: 0%
Stage 2: 35%
Stage 2: 67%
Stage 2: 84%
Stage 2: 89%
Stage 2: 93%
Stage 2: 94%
Stage 2: 96%
Stage 2: 97%
Stage 2: 98%
Stage 2: 99%
Stage 2: 100%
Stage 1: 0%
Stage 1: 100%
Stage 2: 0%
Stage 2: 100%
**
Stage 1: 0%
Stage 1: 100%
Stage 2: 0%
Stage 2: 79%
Stage 2: 99%
Stage 2: 100%
**
Stage 1: 0%
Stage 1: 100%
Stage 2: 0%
Stage 2: 100%
**
Stage 1: 0%
Stage 1: 100%
Stage 2: 0%
Stage 2: 89%
Stage 2: 100%
***
*
Stage 1: 0%
Stage 1: 100%
Stage 2: 0%
Stage 2: 100%
Stage 1: 0%
Stage 1: 100%
Stage 2: 0%
Stage 2: 35%
Stage 2: 75%
Stage 2: 90%
Stage 2: 93%
Stage 2: 95%
Stage 2: 96%
Stage 2: 97%
Stage 2: 98%
Stage 2: 99%
Stage 2: 100%
**
Stage 1: 0%
Stage 1: 100%
Stage 2: 0%
Stage 2: 89%
Stage 2: 100%
**
Stage 1: 0%
Stage 1: 100%
Stage 2: 0%
Stage 2: 35%
Stage 2: 75%
Stage 2: 90%
Stage 2: 93%
Stage 2: 95%
Stage 2: 96%
Stage 2: 97%
Stage 2: 98%
Stage 2: 99%
Stage 2: 100%
**
Stage 1: 0%
Stage 1: 100%
Stage 2: 0%
Stage 2: 45%
Stage 2: 82%
Stage 2: 92%
Stage 2: 95%
Stage 2: 97%
Stage 2: 98%
Stage 2: 99%
Stage 2: 100%
**
Stage 1: 0%
Stage 1: 100%
Stage 2: 0%
Stage 2: 45%
Stage 2: 82%
Stage 2: 92%
Stage 2: 95%
Stage 2: 97%
Stage 2: 98%
Stage 2: 99%
Stage 2: 100%
Start merging...
Could not build fai index /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa.fai
Could not build fai index /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa.fai
[bwa_index] Pack FASTA... [bwa_index] Pack FASTA... 0.00 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] Pack FASTA... 0.00 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.00 seconds elapse.
[bwa_index] Update BWT... [bwa_index] 0.00 seconds elapse.
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Pack forward-only FASTA... 0.00 sec
[bwa_index] Construct BWT for the packed sequence...
0.00 sec
[bwa_index] Pack forward-only FASTA... 0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.00 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa
[main] Real time: 0.015 sec; CPU: 0.009 sec
0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.00 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa
[main] Real time: 0.021 sec; CPU: 0.011 sec
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[bwa_index] 0.01 seconds elapse.
[bwa_index] Update BWT... [main] Version: 0.7.17-r1188
[main] CMD: bwa mem -a /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa
[main] Real time: 0.003 sec; CPU: 0.005 sec
0.00 sec
[bwa_index] Pack forward-only FASTA... [M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 42 sequences (6250 bp)...
0.00 sec
[bwa_index] Construct SA from BWT and Occ... [M::mem_process_seqs] Processed 42 reads in 0.007 CPU sec, 0.007 real sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -a /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa
[main] Real time: 0.012 sec; CPU: 0.011 sec
0.01 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/64_1/contigs.fa
[main] Real time: 0.041 sec; CPU: 0.031 sec
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 420 sequences (55464 bp)...
[M::mem_process_seqs] Processed 420 reads in 0.058 CPU sec, 0.058 real sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -a /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/64_1/contigs.fa /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/64_1/contigs.fa
[main] Real time: 0.062 sec; CPU: 0.063 sec
rm: cannot remove ‘/hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa.fai’: No such file or directory
[fai_build_core] malformed line
Could not build fai index /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa_no_dup.fa.merged.fa.fai
[fai_build_core] malformed line
Could not build fai index /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa_no_dup.fa.merged.fa.fai
[fai_build_core] malformed line
Could not build fai index /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa_no_dup.fa.merged.fa.fai
[bwa_index] Pack FASTA... [fai_build_core] malformed line
Could not build fai index /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa_no_dup.fa.merged.fa.fai
0.00 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] Pack FASTA... [bwa_index] 0.00 seconds elapse.
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Pack forward-only FASTA... 0.00 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.00 seconds elapse.
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.00 sec
[bwa_index] Pack forward-only FASTA... 0.00 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa_no_dup.fa.merged.fa
[main] Real time: 0.024 sec; CPU: 0.007 sec
0.00 sec
[bwa_index] Construct SA from BWT and Occ... [M::bwa_idx_load_from_disk] read 0 ALT contigs
0.00 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa_no_dup.fa.merged.fa
[main] Real time: 0.021 sec; CPU: 0.007 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -a /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa_no_dup.fa.merged.fa /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa_no_dup.fa.merged.fa
[main] Real time: 0.004 sec; CPU: 0.003 sec
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -a /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa_no_dup.fa.merged.fa /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa_no_dup.fa.merged.fa
[main] Real time: 0.003 sec; CPU: 0.003 sec
rm: cannot remove ‘/hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa_no_dup.fa.merged.fa.fai’: No such file or directory
rm: cannot remove ‘/hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa_no_dup.fa.merged.fa.fai’: No such file or directory
[fai_build_core] malformed line
Could not build fai index /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa_no_dup.fa.merged.fa.no_dup.fa.fai
[fai_build_core] malformed line
Could not build fai index /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa_no_dup.fa.merged.fa.no_dup.fa.fai
[fai_build_core] malformed line
Could not build fai index /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa_no_dup.fa.merged.fa.no_dup.fa.fai
[fai_build_core] malformed line
Could not build fai index /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa_no_dup.fa.merged.fa.no_dup.fa.fai
[bwa_index] Pack FASTA... [bwa_index] Pack FASTA... 0.00 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.00 seconds elapse.
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Pack forward-only FASTA... 0.00 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.00 seconds elapse.
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Pack forward-only FASTA... 0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.00 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa_no_dup.fa.merged.fa.no_dup.fa
[main] Real time: 0.017 sec; CPU: 0.007 sec
0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.00 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa_no_dup.fa.merged.fa.no_dup.fa
[main] Real time: 0.015 sec; CPU: 0.008 sec
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -a /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa_no_dup.fa.merged.fa.no_dup.fa /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa_no_dup.fa.merged.fa.no_dup.fa
[main] Real time: 0.002 sec; CPU: 0.003 sec
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -a /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa_no_dup.fa.merged.fa.no_dup.fa /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa_no_dup.fa.merged.fa.no_dup.fa
[main] Real time: 0.002 sec; CPU: 0.003 sec
rm: cannot remove ‘/hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa_no_dup.fa.merged.fa.no_dup.fa.fai’: No such file or directory
rm: cannot remove ‘/hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa_no_dup.fa.merged.fa.no_dup.fa.fai’: No such file or directory
[bwa_index] Pack FASTA... 0.00 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.00 seconds elapse.
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Pack forward-only FASTA... 0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.01 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/64_1/contigs.fa_no_dup.fa.merged.fa
[main] Real time: 0.030 sec; CPU: 0.018 sec
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 82 sequences (21702 bp)...
[M::mem_process_seqs] Processed 82 reads in 0.100 CPU sec, 0.099 real sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -a /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/64_1/contigs.fa_no_dup.fa.merged.fa /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/64_1/contigs.fa_no_dup.fa.merged.fa
[main] Real time: 0.103 sec; CPU: 0.104 sec
[bwa_index] Pack FASTA... 0.00 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.00 seconds elapse.
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Pack forward-only FASTA... 0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.00 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/64_1/contigs.fa_no_dup.fa.merged.fa.no_dup.fa
[main] Real time: 0.035 sec; CPU: 0.016 sec
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 47 sequences (12377 bp)...
[M::mem_process_seqs] Processed 47 reads in 0.020 CPU sec, 0.020 real sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -a /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/64_1/contigs.fa_no_dup.fa.merged.fa.no_dup.fa /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/64_1/contigs.fa_no_dup.fa.merged.fa.no_dup.fa
[main] Real time: 0.023 sec; CPU: 0.024 sec
Running command: ./TERefiner_1 -P -b /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa.itself.sort.bam -r /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa -o /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa_no_dup.fa -c 0.99 -g ...
Running command: ./ContigsMerger -s 0.4 -i1 -2.0 -i2 -2.0 -x 12 -y 50 -k 10 -t 5 -m 1 -o /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa_no_dup.fa.merge.info /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa_no_dup.fa > /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa_no_dup.fa.merged.fa ...
Running command: ./TERefiner_1 -P -b /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa_no_dup.fa.merged.fa.itself.sort.bam -r /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa_no_dup.fa.merged.fa -o /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa_no_dup.fa.merged.fa.no_dup.fa -c 0.99 -g ...
Running command: ./TERefiner_1 -P -b /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa_no_dup.fa.merged.fa.no_dup.fa.itself.sort.bam -r /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa_no_dup.fa.merged.fa.no_dup.fa -o /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa_no_dup.fa.merged.fa.no_dup.fa.no_contained.fa -c 0.99 ...
Running command: ./TERefiner_1 -P -b /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa.itself.sort.bam -r /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa -o /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa_no_dup.fa -c 0.99 -g ...
Running command: ./ContigsMerger -s 0.4 -i1 -2.0 -i2 -2.0 -x 12 -y 50 -k 10 -t 5 -m 1 -o /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa_no_dup.fa.merge.info /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa_no_dup.fa > /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa_no_dup.fa.merged.fa ...
Running command: ./TERefiner_1 -P -b /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa_no_dup.fa.merged.fa.itself.sort.bam -r /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa_no_dup.fa.merged.fa -o /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa_no_dup.fa.merged.fa.no_dup.fa -c 0.99 -g ...
Running command: ./TERefiner_1 -P -b /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa_no_dup.fa.merged.fa.no_dup.fa.itself.sort.bam -r /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa_no_dup.fa.merged.fa.no_dup.fa -o /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa_no_dup.fa.merged.fa.no_dup.fa.no_contained.fa -c 0.99 ...
Running command: ./TERefiner_1 -P -b /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/64_1/contigs.fa.itself.sort.bam -r /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/64_1/contigs.fa -o /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/64_1/contigs.fa_no_dup.fa -c 0.99 -g ...
Running command: ./ContigsMerger -s 0.4 -i1 -2.0 -i2 -2.0 -x 12 -y 50 -k 10 -t 5 -m 1 -o /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/64_1/contigs.fa_no_dup.fa.merge.info /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/64_1/contigs.fa_no_dup.fa > /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/64_1/contigs.fa_no_dup.fa.merged.fa ...
Running command: ./TERefiner_1 -P -b /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/64_1/contigs.fa_no_dup.fa.merged.fa.itself.sort.bam -r /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/64_1/contigs.fa_no_dup.fa.merged.fa -o /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/64_1/contigs.fa_no_dup.fa.merged.fa.no_dup.fa -c 0.99 -g ...
Running command: ./TERefiner_1 -P -b /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/64_1/contigs.fa_no_dup.fa.merged.fa.no_dup.fa.itself.sort.bam -r /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/64_1/contigs.fa_no_dup.fa.merged.fa.no_dup.fa -o /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/64_1/contigs.fa_no_dup.fa.merged.fa.no_dup.fa.no_contained.fa -c 0.99 ...
[bwa_index] Pack FASTA... [bwa_index] Pack FASTA... [bwa_index] Pack FASTA... 0.00 sec
[bwa_index] Construct BWT for the packed sequence...
0.00 sec
[bwa_index] Construct BWT for the packed sequence...
0.00 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.00 seconds elapse.
[bwa_index] Update BWT... [bwa_index] 0.00 seconds elapse.
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Pack forward-only FASTA... 0.00 sec
[bwa_index] Pack forward-only FASTA... [bwa_index] 0.00 seconds elapse.
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.00 sec
0.00 sec
[bwa_index] Pack forward-only FASTA... [main] Version: 0.7.17-r1188
[main] CMD: bwa index /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/1_1/contigs.fa
[main] Real time: 0.017 sec; CPU: 0.012 sec
0.00 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa
[main] Real time: 0.018 sec; CPU: 0.012 sec
0.01 sec
[bwa_index] Construct SA from BWT and Occ... [M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::bwa_idx_load_from_disk] read 0 ALT contigs
0.00 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/64_1/contigs.fa
[main] Real time: 0.029 sec; CPU: 0.018 sec
[M::process] read 2 sequences (590 bp)...
[M::process] read 2 sequences (590 bp)...
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 2 sequences (590 bp)...
[M::mem_process_seqs] Processed 2 reads in 0.002 CPU sec, 0.002 real sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -T 30 -a /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/64_1/contigs.fa /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/../flank_regions/64_1.fa
[main] Real time: 0.004 sec; CPU: 0.007 sec
Traceback (most recent call last):
  File "./main.py", line 283, in <module>
    main_func(scommand,sfconfig)
  File "./main.py", line 274, in main_func
    gap_assembler.assemble_pipeline()
  File "/hpcdata/bcbb/homc/conda_envs/envs/GAPPadder/assemble_gaps.py", line 339, in assemble_pipeline
    id_remain=self.pick_already_constructed(contigs_select, fa_list, sf_picked)
  File "/hpcdata/bcbb/homc/conda_envs/envs/GAPPadder/assemble_gaps.py", line 321, in pick_already_constructed
    m_picked=contigs_select.get_already_picked(sf_picked)
  File "/hpcdata/bcbb/homc/conda_envs/envs/GAPPadder/pick_contigs.py", line 576, in get_already_picked
    with open(sf_picked) as fin_picked:
IOError: [Errno 2] No such file or directory: u'/hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/../picked_seqs.fa'
```

Going back to the first error which is `Could not build fai index /hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout/merged/velvet_temp/9_1/contigs.fa.fai` I went to this file and found that of course it can't index the fasta, it looks like this:

velvet_temp/9_1/contigs.fa.fai:
```
(GAPPadder) [homc@ai-hpcn106 9_1]$ less contigs.fa
Arrange error! 0 5
```

Tracing backwards, this is an error provided by ContigsCompactor.cpp
https://github.com/simoncchu/GAPPadder/blob/a3597506c5ad0bbbf4e72938e47829ede3c47afe/ContigsCompactor-v0.2.0/ContigsMerger/ContigsCompactor.cpp#L707

However, I don't know how to troubleshoot further. Why is Contigs Compactor returning an Arange error and how can I fix the pipeline? 

This is my json file. SAMTools, BWA were installed using Conda, I recompiled Velvet during install to use MAXKMERLENGTH=99.

```
{
    "draft_genome": {
        "fa": "/hpcdata/bcbb/homc/multipilon_pb_gIllumina/Tcas_blobtools_round3_gIlluminabasecovatleast1_or_RNAseqgt1.pilon10.fasta"
    },
    "raw_reads": [
		    {
		        "left": "/hpcdata/bcbb/homc/Tcas_gIllumina.trim.1.fastq",
		        "right": "/hpcdata/bcbb/homc/Tcas_gIllumina.trim.2.fastq"
		    }	  ],
    "alignments": [
		    {
            "bam": "/hpcdata/bcbb/homc/multipilon_pb_gIllumina/Tcas_HISAT2_trim_gIllumina_map_Tcas_blobtools_round3_gIlluminabasecovatleast1_or_RNAseqgt1_pilon10/Tcas_HISAT2_trim_gIllumina_map_Tcas_blobtools_round3_gIlluminabasecovatleast1_or_RNAseqgt1_pilon10.bam",
		        "is": "148",
		        "std": "50"
        }
	  ],
    "software_path": {
        "bwa": "bwa",
        "samtools": "samtools",
        "velvet": "/hpcdata/bcbb/homc/conda_envs/envs/GAPPadder/velvet",
        "kmc": "/hpcdata/bcbb/homc/conda_envs/envs/GAPPadder/bin/",
        "TERefiner": "./TERefiner_1",
        "ContigsMerger": "./ContigsMerger"
    },
    "parameters": {
    		"working_folder": "/hpcdata/bcbb/homc/multipilon_pb_gIllumina/GAPPadderout",
        "min_gap_size": "100",
        "flank_length": "300",
        "nthreads": "15",
        "verbose": "1"
		},
		"kmer_length": [{
						"k": 30,
						"k_velvet": [{
								"k": 29
						}, 
						{
								"k": 27
						}]
				}, 
				{
						"k": 40,
						"k_velvet": [{
								"k": 39
						}, 
						{
								"k": 37
						}]
				},
				{
						"k": 50,
						"k_velvet": [{
								"k": 49
						}, 
						{
								"k": 47
						}]
				}]
}
```

Please let me know what you think. Would really like to use this tool, and have spent several hours troubleshooting and I am running up against a wall.

Sincerely,
Margaret

**Comment by Mailinnia** [comment]
Did you ever find a solution to this?
Because I am running into the same issues.

**Comment by margaretc-ho** [comment]
No, I ended up using tools for long read gap filling like samba and TGS-gapcloser and then just polishing with short reads and pilon
