### ISSUE TITLE
merge_dispatch_reads_for_gaps_v2 step throwing "IndexError: list index out of range"

### ISSUE THREAD

**Issue by jos4uke** [Reedwarbler/GAPPadder#3]
Hi

I am currently running GAPPadder on some short reads assembly but getting this error at merge_dispatch_reads_for_gaps_v2 step

`python ./GAPPadder/main.py -c All -g GAPPadder_configuration_CLC.json`
  
>Traceback (most recent call last):
>  File "./GAPPadder/main.py", line 283, in <module>
>    main_func(scommand,sfconfig)
>  File "./GAPPadder/main.py", line 257, in main_func
>    drc.merge_dispatch_reads_for_gaps_v2(left_reads, right_reads)
>  File "./GAPPadder/run_multi_threads_discordant.py", line 213, in merge_dispatch_reads_for_gaps_v2
>    temp_field=id_fields[0].split("/")
>IndexError: list index out of range
 
Any idea why this error occured?

Thanks in advance

**Comment by jos4uke** [comment]
I can close this issue, it was the input reads.
I didn't check that GAPPadder expects only fastq and no compressed fastq.
